"project_identifier": "vuetify"
"api_key_env": CROWDIN_API_KEY
"base_path_env": CROWDIN_BASE_PATH
"preserve_hierarchy": true
"files": [
  {
    "source": "packages\\vuetifyjs.com\\lang\\en-US\\**\\*.json",
    "translation": "packages\\vuetifyjs.com\\lang\\%locale%\\**\\%original_file_name%",
  }
]
